### ISSUE TITLE
IMPROVEMENTS: Rename "I'd rather use passcode" button to a new one

### ISSUE THREAD

**Issue by elahonoridez** [idpass/inji#10]
After greying out 'Use biometrics' option -> it displays 'I'd rather use passcode'. 
Suggest changing text to 'Use passcode'

<img src="https://user-images.githubusercontent.com/75471103/150729350-7a720c4b-224f-4e93-b2c5-a9041f938a31.jpg" width="300" height="700">

**Comment by kneckinator** [comment]
We will not do this. Closing it.
