### ISSUE TITLE
"Show this QR code to request a VC" displayed when sharing VC is already in process

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#116]
**Describe the bug**
When connection has been established the QR code is no longer displayed on the requesting device. However, the text "Show this QR code to request a VC" is still displayed.

**To Reproduce**
1. Initiate sharing
2. Scan QR code
3. Note that QR code is no longer displayed but text is there.

**Expected behavior**
The text "Show this QR code to request a VC" should not be displayed when connection has been established and QR code is no longer displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/36752902/158967045-bbbce0f5-a8c9-4f50-bd12-5e5665ebb713.png)

**Comment by jannahadlaon** [comment]
Verified on 0.3.0-rc5 v1.1.2. Working as expected.
