### ISSUE TITLE
Text corrections

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#123]
**Describe the bug**
Two texts need correction:

1. on popup displayed on receiving device after successful transfer. replace "DEVICENAME's ID has been successfully received" with "ID has been successfully received from DEVICENAME"
2. When rejecting a VC there is a trailing apostrophe on the displayed popup: "You rejected DEVICENAME's ID**'**"

**Reproduced on**
0.2.1 rc3

**Comment by jannahadlaon** [comment]
Verified on 0.3.0 v1.1.5 qa3. Working as expected.
