### ISSUE TITLE
Header on ID downloaded through VID should say "VID"

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#126]
**Describe the bug**
When downloading an ID using VID (rather than UIN) the field at top middle of the ID still has the label "UIN" (see screenshot).

**To Reproduce**
1. Get ID by selecting "VID" in dropdown and entering a VID number
2. Once download is completed, enter ID and note top middle field (see screenshot)

**Expected behavior**
Header of field should be "VID" instead of "UIN".

**Screenshots**

**Encountered on:**
0.2.1

**Additional context**
Report by MOSIP as MID-3

![mobapp](https://user-images.githubusercontent.com/36752902/159424034-e0d52548-a021-4f93-a5e7-46a25e9b8d14.png)

**Comment by jannahadlaon** [comment]
Verified on 0.3.0-qa3-v1.1.5 . Working as expected.
