### ISSUE TITLE
Successfully build the app on iOS

### ISSUE THREAD

**Issue by kneckinator** [idpass/inji#129]
The app should:
- Start

**Comment by kneckinator** [comment]
@nicholemnl This is done, right?

**Comment by nicholemnl** [comment]
Hi Ken it would be in on this branch [feature/ios-129](https://github.com/idpass/inji/tree/feature/ios-129)

However, just to note, this can't be merged to develop yet since I have to remove some of the feature that was causing some issue in IOS.

**Comment by jannahadlaon** [comment]
Tested on **iOS build version 0.4.0 (3)**
Verified that the iOS build can be installed, launched, and set up.

Test devices:
- iPhone 11 (iOS 15.5)
- iPhone SE (iOS 15.4)

**Works as expected**
