### ISSUE TITLE
iOS - basic functionality

### ISSUE THREAD

**Issue by kneckinator** [idpass/inji#130]
The app should have basic functionality on iOS, except for the VC sharing.

This means that it should be possible to:
- Create a passcode
- Navigate the screens

**Comment by kneckinator** [comment]
This is done, right? Were you able to download a VC when running on iOS so that other screens could be tested?

**Comment by nicholemnl** [comment]
Yes @kneckinator

**Comment by kneckinator** [comment]
This is done in the yet to be merged branch referenced from #129
