### ISSUE TITLE
Scan QR code screen is not properly updated when location is enabled 

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#14]
Current behaviour:
    1. Go to SCAN (second icon from left)
    2. Device asks to turn on device location
    2. Click “No thanks”
    3. Error message is displayed
    4. Activate location on device
    5. Swap screen to refresh
    6. Message is displayed about allowing camera
    7. Click “Deny”
    8. Error message is displayed
    9. Click “Allow access to camera”
    10. Taken to settings
    11. Allow access to camera
    12. Go back to app
    13. Swap screen to refresh
    14. Instead of seeing camera the screen is white, "Scan QR Code" is displayed on the top and the icons on the bottom, but no camera is displayed

Expected behaviour:
App should either display camera or error message that location access must be given to the app.

**Comment by pmigueld** [comment]
Should already be fixed by this PR: https://github.com/idpass/inji/pull/51
Please verify.

**Comment by kneckinator** [comment]
@celinenilla this was not on the project board previously, but from the links @pmigueld shared this should be fixed in 0.2.1. I am adding the milestone and a project to this issue.
