### ISSUE TITLE
All data is not included in "Address" field

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#147]
**Describe the bug**
When downloading a VC, only postal code is displayed. Data like region and province code is missing

**To Reproduce**
1. Generate VC using 
2. Note that only postal code is displayed

**Expected behavior**
All included data should be displayed

**Reproduced on:**
0.2.1 RC3

**Additional context**
Reported by Anushree at MOSIP

**Screenshots**
![WhatsApp Image 2022-04-04 at 13 33 39](https://user-images.githubusercontent.com/36752902/161509443-f9b8eeeb-17c2-45b4-b4ea-3eb5254d35b9.jpeg)

**VC data as included below**
[Untitled.txt](https://github.com/idpass/inji/files/8408214/Untitled.txt)

**Comment by kneckinator** [comment]
@pmigueld what do you think the effort would be to solve this?
