### ISSUE TITLE
{{vcLabel}} is displayed instead of actual label on the Download ID screen

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#161]
**Describe the bug**
On the download ID screen the label has been replaced by {{vcLabel}}

**To Reproduce**
1. Go to 'Download ID screen
2. note that it says {{vcLabel}}

**Expected behavior**
Correct label should be displayed

**Identified on:**
0.3.0 RC1

**Screenshots**
![Image from iOS (5)](https://user-images.githubusercontent.com/36752902/165228324-e65e4586-77a1-42b8-9d47-9257ce1c820a.jpg)

**Comment by jannahadlaon** [comment]
Verified on test build that:

- ID is displayed instead of {{vcLabel}}
- behavior is correct when editing label
- works as expected after changing the language to Filipino
Working as expected

**Comment by celinenilla** [comment]
Tested on 0.3.0 RC2 1.1.5. Working as expected
