### ISSUE TITLE
Not possible to change VC during generation after receiving error message 

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#164]
**Describe the bug**
When selecting incorrect type of VC (VID vs UIN) and getting an error message it is not possible to select the other type

**To Reproduce**
1. Click "Add ID"
2. Select "VID" in dropdown
3. Enter UIN number, for instance "3415749807"
4. Error message is displayed
5. Click dropdown and try to select "UIN"
6. Note that this is not possible and dropdown will remain on VID

**Expected behavior**
It should be possible to change between UIN and VID also after receiving an error message

**Encountered on**
0.3.0 rc1

**Additional context**
Also reported by MOSIP as [MID-17](https://mosip.atlassian.net/servicedesk/customer/portal/15/MID-17)

**Comment by jannahadlaon** [comment]
Verified on test build. Working as expected

**Comment by celinenilla** [comment]
Verified on 0.3.0. Working as expected.
