### ISSUE TITLE
Issue when unlocking/locking a VC

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#166]
**Describe the bug**
When trying to lock a VC i get the screen for passcode (works OK) and then the screen for OTP. When entering OTP (111111) nothing happens and I remain on the same screen, the only way to exit is to close and reopen the app. After reopening the app the VC has been unlocked, so operation has worked.

**To Reproduce**
1. Go to VC
2. Click on three dots and select "Unlock"
3. Enter passcode
4. Enter OTP
5. Note that nothing happens
6. Close and reopen app
7. Enter VC, click three dots and note that it now says "Unlock"

**Expected behavior**
App should proceed when OTP has been entered

**Reproduced on**
0.3.0 RC1

**Comment by jannahadlaon** [comment]
Verified on test build. Working as expected.
