### ISSUE TITLE
Getting "Request network failed" when trying to unlock a VC

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#172]
**Describe the bug**
When trying to unlock a VC the error message Getting "Request network failed" is displayed. 

**To Reproduce**
1. Enter a VC and click on three dots in top right corner
2. Verify that options are "Lock", "Rename", "Revoke" and "Delete"
3. Click "Lock"
4. "Request network failed" is displayed

**Expected behavior**
No error message should be displayed and VC should be unlocked

**Reproduced on**
0.3.0rc2 1.1.5

**Comment by kneckinator** [comment]
There is a build for this change at https://github.com/idpass/inji/actions/runs/2238419712
