### ISSUE TITLE
Remove Lock/Unlock options in VC

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#178]
**Describe the bug**
Due to new requirements for https://github.com/idpass/inji/issues/133 we'll need to redesign the feature. Since this will not be done for 0.3.0 we need to remove https://github.com/idpass/inji/issues/133 from 0.3.0.

**Expected behavior**
Lock / Unlock should no longer be available in VC

**Comment by kneckinator** [comment]
The change #178 will not be reverting/removing the lock/unlock code but it will hide the functionality so that the user cannot see it.
