### ISSUE TITLE
Create MOSIP profile for the build process

### ISSUE THREAD

**Issue by kyanthony** [idpass/inji#182]
We need a MOSIP profile for the build process. The same needs to be updated in Inji's README file as well.

![image (1)](https://user-images.githubusercontent.com/104809480/167606963-b6509b0e-f84c-4be5-944c-49456226d75a.png)

**Comment by rjmangubat23** [comment]
@kyanthony @jeremi for the MOSIP Profile is `npm run build:android:mosip` the right one to name it?

**Comment by jeremi** [comment]
Ok, let's go with this.
