### ISSUE TITLE
Add backend info to the settings page

### ISSUE THREAD

**Issue by kneckinator** [idpass/inji#188]
In https://github.com/idpass/mimoto/issues/30 we are adding API endpoints to show us:
- The version string of Mimoto 
- The URL/URI of the MOSIP server Mimoto is connected to

This issue is about making calls to these API:s from the "profile" page of Inji to add this information below the current version string like this:

**newlogic-0.3.0-rc1** (current string – Inji APK version)
**Mimoto: 1.2.0-SNAPSHOT**
**MOSIP: https://qa3.mosip.net**

**Comment by danicaerediano** [comment]
@kneckinator is this under developer settings?

**Comment by pmigueld** [comment]
@danicaerediano no, this is not the backend URL configuration; this is to add more info to the text at the bottom of the profile screen. I believe this requires something from the backend first right @uocnb? An endpoint we can query to check the version of MOSIP it's running.

**Comment by uocnb** [comment]
@pmigueld yes, it's required a new backend API for this information.
