### ISSUE TITLE
Scan screen should subscribe to changes for camera permission

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#23]
Current behaviour:
In the following scenario:

1. On phone B (scanning phone), turn off app permission to access camera
2. On phone A (requesting phone), go to REQUEST (third icon from left)
3. On phone B (sending phone) go to SCAN (second icon from left) – popup is displayed asking to activate camera
4. Click “Deny” – message is displayed informing that camera is needed with button "Allow access to camera"
5. On phone B, Go to “Home” page
6. On phone B (scanning phone) go to SCAN (second icon from left) – message is displayed informing that camera is needed with button "Allow access to camera"
7. Click “Allow access to camera” – taken to settings
8. On phone B, allow access to camera
9. Go back to app

the text “This app uses the camera...” is still displaying on SCAN screen. As a user it is unclear that I need to shift screen and go back in order to activate the camera.

Expected behaviour:
SCAN screen should automatically refresh and display scanning screen when camera permission has been enabled.

**Comment by danicaerediano** [comment]
tested and verified Scan screen is already subscribing to changes for camera permission
