### ISSUE TITLE
App should ask for permission to location access when opening Scan QR page

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#29]
Current behaviour:
When turning of permission to location for the app and entering the Scan QR code, the camera is activated and it is possible to scan the QR code. However, after scanning the code it is not possible to connect.

Expected behaviour:
Camera should not be activated when app does not have permission to location access. User should be made aware that this is an issue. @ken to advise on exact functionality.

**Comment by pmigueld** [comment]
@danicaerediano to clarify, that screen and error is only checking if the Location service is on/off. We need to add a check for the **permission** as well if it's been denied at some point.

**Comment by danicaerediano** [comment]
@pmigueld a popup to enable location always appear

**Comment by danicaerediano** [comment]
@celinenilla is this not fixed on the latest build?

**Comment by pmigueld** [comment]
@danicaerediano a popup to enable location exists. We don't have one to **allow location permissions** if it's been denied before on the Scan Screen.

Can you try this:
1. Deny location permission
2. Go to Scan Screen
3. (popup to enable location appears) Tap enable
4. Share a VID
5. (does it connect? and did enabling the location also allow the permission?)

**Comment by kneckinator** [comment]
Added to the project and milestone 0.2.1

**Comment by celinenilla** [comment]
Tested on [80c8f6c](https://github.com/idpass/inji/actions/runs/1949399399). Working as expected.

**Comment by celinenilla** [comment]
Verified on 0.2.0rc3. Working as expected.
