### ISSUE TITLE
It should be possible to switch camera used for QR code scanning

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#5]
Suggested enhancement:
The QR scanning will currently only use the front camera. In cases where front camera is not functioning it would be good to be able to switch to use selfie camera instead.

**Comment by kneckinator** [comment]
@jeremi I added the triage label to this ticket even though the code is ready so that we can understand whether we'll embed this in the app. We could ask how MOSIP would reason about it.

**Comment by kneckinator** [comment]
@jeremi Removed the triage label. This has already been merged. Let's test it and show it to MOSIP. We can always revert.

**Comment by celinenilla** [comment]
Tested on 0.2.1-beta2-newlogic_20220303_1026.apk. Working as expected.

**Comment by celinenilla** [comment]
Verified on 0.2.0rc3. Working as expected.
