### ISSUE TITLE
Upgrade to signature V2

### ISSUE THREAD

**Issue by jeremi** [idpass/inji#56]
From Mobsf: 
> Application is signed with v1 signature scheme, making it vulnerable to Janus vulnerability on Android 5.0-8.0, if signed only with v1 signature scheme. Applications running on Android 5.0-7.0 signed with v1, and v2/v3 scheme is also vulnerable

**Comment by typelogic** [comment]
https://github.com/mosip/inji/pull/12

**Comment by typelogic** [comment]
https://github.com/idpass/inji/pull/59

**Comment by kneckinator** [comment]
Checked in MobSF on 0.2.1-beta4 and still seems to be using V1.
https://mobsf.newlogic.dev/static_analyzer/?name=io.mosip.residentapp-0.2.1-beta4-newlogic_20220304_1058.apk&checksum=063628379a68cdc5c22b686c0e2a0011&type=apk
