### ISSUE TITLE
Disable Clear text traffic

### ISSUE THREAD

**Issue by jeremi** [idpass/inji#57]
From MobSF:
> The app intends to use cleartext network traffic, such as cleartext HTTP, FTP stacks, DownloadManager, and MediaPlayer. The default value for apps that target API level 27 or lower is "true". Apps that target API level 28 or higher default to "false". The key reason for avoiding cleartext traffic is the lack of confidentiality, authenticity, and protections against tampering; a network attacker can eavesdrop on transmitted data and also modify it without being detected.

**Comment by typelogic** [comment]
https://github.com/mosip/inji/pull/13
