### ISSUE TITLE
Issue: Cancel button on the OTP code screen

### ISSUE THREAD

**Issue by elahonoridez** [idpass/inji#6]
ISSUE: In OTP/verification code screen in the app -> cancel button X on the top right is not working
(Originally reported by Rakhi of MOSIP)

Use Case 1: When a user just wants to cancel or exits out of the screen, the cancel button is not working.
Use Case 2: When OTP expires and user cannot get back to UI for resending the OTP option because the cancel button X is not working.

<img src="https://user-images.githubusercontent.com/75471103/150728975-19a09f21-ad3d-49f7-aace-52a237581e1e.jpg" width="300" height="700">

**Comment by danicaerediano** [comment]
@celinenilla can you please check again with the recent build? 
tested and it works fine as expected
1.) enter UIN
2.) Click generate Build
3.) OTP screen pops up
4.) Closed OTP screen
5.) UIN is not cleared

**Comment by celinenilla** [comment]
Verified on 0.2.0rc3. Working as expected.
