### ISSUE TITLE
Validate VID

### ISSUE THREAD

**Issue by kneckinator** [idpass/inji#8]
Embedded proof only for phase 1

**Comment by pmigueld** [comment]
I've added the missing files in my branch and so far no build errors using the forked version that's compatible with React Native. The current issue I'm resolving is this error when attempting to verify a credential: 
```
VALIDATION STATUS:  Object {
  "error": [VerificationError: Verification error(s).],
  "results": Array [
    Object {
      "error": [Error: crypto.subtle not found.],
      "proof": Object {
      ...
```

Updated estimate is 2 more days. TODOs left:
- [ ] fix error with missing `crypto.subtle`
- [ ] test on local sample data
- [ ] test on live backend data

**Comment by pmigueld** [comment]
Listing other potential libraries we can use:

- [Veramo](https://veramo.io/docs/react_native_tutorials/react_native_setup_identifers/)
  - **Caveat**: uses `rn-nodeify` to hack NodeJS modules into React Native
  
- [verifiable-credentials-java](https://github.com/danubetech/verifiable-credentials-java)
  - We will need to create a React Native plugin to use it in the app

**Comment by celinenilla** [comment]
Verified on 0.3.0 RC2 1.1.5. Working as expected.
Created test case TSRA-52.
