### ISSUE TITLE
Crash/Error should be reported 

### ISSUE THREAD

**Issue by jeremi** [idpass/inji#9]
Add support for reporting logs/errors in Google Firebase / Sentry.

By default we should not provide the config, we will inject it only in builds we do.

**Comment by jeremi** [comment]
@rjmangubat23 can you update with your status?

**Comment by rjmangubat23** [comment]
@jeremi still in progress with this, I have already locally setup Sentry on my end the only thing remaining is adding config for setting flag via `app.config.js`.

**Comment by kneckinator** [comment]
@rjmangubat23 Has there been any progress on this?

**Comment by kneckinator** [comment]
Now that we have implemented #77 can we close this?

**Comment by rjmangubat23** [comment]
yes I agree @kneckinator, If they need something more advanced we can then implement Sentry. @jeremi what do you think?

**Comment by jeremi** [comment]
Yes, I'm good with it.
