### ISSUE TITLE
Interoperable iOS and Android versions

### ISSUE THREAD

**Issue by kneckinator** [idpass/inji#94]
This would use a unified protocol, i.e. Google Nearby Messages

**Comment by kyanthony** [comment]
The cross-platform communication will use Google Nearby Messages API, as it works on both iOS and Android. As Google Nearby Messages requires internet connectivity, there is a need to be able to switch the app between a strict offline protocol such as Google Nearby Communications/ID PASS SmartShare and a method requiring connectivity.
The toggle between online/offline also ensures that the device discovery done using Bluetooth LE (BLE) works as expected with the least possible interference.
